### ISSUE TITLE
Proxy Configuraton Broken/HTTP(S) Agent not being passed on JWKSet Creation

### ISSUE THREAD

**Issue by indeed404** [auth0/node-oauth2-jwt-bearer#102]
v.1.4.0 of the library is broken when running behind a proxy

The "agent" parameter which is passed to the get-key-function isn't listed as an input parameter in the JWKSOptions, it should be put here:

https://github.com/auth0/node-oauth2-jwt-bearer/blob/8203cebe6c3dc6f3f981e0eb64b8b57fc0a5150d/packages/access-token-jwt/src/get-key-fn.ts#L16

the "agent" input parameter should then also be passed to the createRemoteJWKSet function in this line:

https://github.com/auth0/node-oauth2-jwt-bearer/blob/8203cebe6c3dc6f3f981e0eb64b8b57fc0a5150d/packages/access-token-jwt/src/get-key-fn.ts#L31

**Comment by indeed404** [comment]
Created a PR https://github.com/auth0/node-oauth2-jwt-bearer/pull/103

**Comment by adamjmcgrath** [comment]
Fixed in https://github.com/auth0/node-oauth2-jwt-bearer/releases/tag/v1.4.1 - thanks asgain @indeed404
