### ISSUE TITLE
[docs] 404 error in the GitHub Pages documentation when clicking on a class or an interface

### ISSUE THREAD

**Issue by maxime-bc** [auth0/node-oauth2-jwt-bearer#106]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer#readme) and [Examples](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-oauth2-jwt-bearer/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

Clicking on any classes or interfaces in the documentation hosted at https://auth0.github.io/node-oauth2-jwt-bearer/ results in a 404 error. I cloned the repo and built the doc locally and the links work, so maybe the hosted version is outdated ?

### Reproduction

1. Go to https://auth0.github.io/node-oauth2-jwt-bearer/
2. Click to any of the links in the `Classes` or `Interfaces` section (e.g. InsufficientScopeError)
3. Get a 404 error from GitHub pages.

### express-oauth2-jwt-bearer version

-

### Node.js version

-

**Comment by adamjmcgrath** [comment]
Thanks for raising this @maxime-bc 

Looks like the filename case must have changed in a typedoc update - will fix

In the meantime, you can change the filename to lower case to see the docs, eg https://auth0.github.io/node-oauth2-jwt-bearer/classes/insufficientscopeerror.html
