### ISSUE TITLE
Getting AssertionError You must provide a 'tokenSigningAlg' for validating symmetric algorithms despite not providing a secret key value pair.

### ISSUE THREAD

**Issue by ryanlohyr** [auth0/node-oauth2-jwt-bearer#121]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer#readme) and [Examples](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-oauth2-jwt-bearer/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
});` 
I have implemented this middleware for my express backend. However when I run the backend I get the error "AssertionError: You must provide a 'tokenSigningAlg' for validating symmetric algorithms". 

### Reproduction

1. Clone https://github.com/auth0-samples/auth0-express-api-samples 
2. Cd /01-Authorization-RS256
3. Follow installation instructions in readme, and change checkJWT into `const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
});`  . Assertion error consistently shown 

### express-oauth2-jwt-bearer version

1.6.0

### Node.js version

v16.14.2

**Comment by ewanharris** [comment]
Hey @ryanlohyr 👋🏻 

Do you have a value set as `process.env.SECRET`? That's what the [code pulls from ](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/access-token-jwt/src/jwt-verifier.ts#L167)

You could try setting `secret` to `undefined` explicitly in the `auth` call to prevent this or change the name of that environment variable.

```js
const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
  secret: undefined
});
```

**Comment by ryanlohyr** [comment]
Hey @ewanharris, thanks for reaching out. Tried it but same error comes up. This line from the [code](https://github.com/auth0/node-oauth2-jwt-bearer/blob/0c15677628d22a10f274133159b2ac43c0392e12/packages/access-token-jwt/src/jwt-verifier.ts#L190C3-L190C3) confuses me as doesn't it mean that if you were to provide a key called 'secret', then you must also provide a key called 'tokenSigningAlg' . So not sure why that assertion gets triggered although a key of 'secret' was not provided. 

However, I did try to do this 
`const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
  tokenSigningAlg: undefined,
  secret: "",
});`. 

And there are no errors, but not sure if this will affect the functionality of the middleware, as my jwt is signed using RS256.

**Comment by ryanlohyr** [comment]
Hi @adamjmcgrath @adamjmcgrath,
Thanks for the help, JWT middleware works with the following 
`const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
  tokenSigningAlg: undefined,
  secret: "",
});`

**Comment by adamjmcgrath** [comment]
HI @ryanlohyr 

You shouldn't need `tokenSigningAlg: undefined` (and you can remove the `secret` if you can remove the `SECRET` environment variable from your environment)

**Comment by ryanlohyr** [comment]
Hi @adamjmcgrath, removed the secret env variable and it works as 
`export const checkJwt = auth({
  audience: process.env.AUDIENCE_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
});`. 
Thanks for the help
