### ISSUE TITLE
Node version limit

### ISSUE THREAD

**Issue by micheleivani** [auth0/node-oauth2-jwt-bearer#41]
Hello, 

I tried to install the package on my node/express project but I got an error because my version node version (16.x.x or 17.x.x) is not supported. Right now node 16 version isLTS but I think you could have just a minimum version of node support, and not a range.

Thank you.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @micheleivani - investigating

**Comment by isaachinman** [comment]
@adamjmcgrath Thanks for merging a fix. Can you release this as soon as possible?

**Comment by adamjmcgrath** [comment]
Hi @isaachinman @micheleivani - this was released in [1.1.0](https://github.com/auth0/node-oauth2-jwt-bearer/releases/tag/v1.1.0)

**Comment by jvenema** [comment]
I'm getting a warning on this still - expected?

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'express-oauth2-jwt-bearer@1.1.0',
npm WARN EBADENGINE   required: { node: '12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.3.0', npm: '7.15.1' }
npm WARN EBADENGINE }

**Comment by adamjmcgrath** [comment]
Hi @jvenema - yep this is expected

This SDK depends on `jose` which requires Node `^16.13.0` see https://github.com/panva/jose/issues/262
