### ISSUE TITLE
InvalidTokenError: Failed to fetch authorization server metadata

### ISSUE THREAD

**Issue by rashidmya** [auth0/node-oauth2-jwt-bearer#50]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I click button in the external page I'm expecting to get the response message from the API server. 

Instead, I get this error in **nodejs server**: 
```
InvalidTokenError: Failed to fetch authorization server metadata
    at C:\Users\BUGA\Documents\VSCODE\Web Projects\fuceti-v2\server\node_modules\express-oauth2-jwt-bearer\dist\index.js:271:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\BUGA\Documents\VSCODE\Web Projects\fuceti-v2\server\node_modules\express-oauth2-jwt-bearer\dist\index.js:354:24
```

and I get this error in **client side vue**:
```
xhr.js?b50d:210 GET http://localhost:8080/api/external 401 (Unauthorized)
dispatchXhrRequest @ xhr.js?b50d:210
xhrAdapter @ xhr.js?b50d:15
dispatchRequest @ dispatchRequest.js?5270:58
request @ Axios.js?0a06:112
Axios.<computed> @ Axios.js?0a06:136
wrap @ bind.js?1d2b:9
_callee$ @ ExternalApi.vue?ac6e:19
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:294
eval @ runtime.js?96cf:119
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
callApi @ ExternalApi.vue?ac6e:19
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
original._wrapper @ vue.runtime.esm.js?2b0e:6961
ExternalApi.vue?ac6e:34 Error: Request failed with status code 401
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.onloadend (xhr.js?b50d:66:1)
```

### Reproduction
I followed the quickstart guides: 
- [Login Guide](https://auth0.com/docs/quickstart/spa/vuejs)
- [API Guide](https://auth0.com/docs/quickstart/spa/vuejs/02-calling-an-api#install-the-axios-package).

### Environment
Windows 10

Server packages:
```
"dependencies": {
    "@types/cors": "^2.8.12",
    "cors": "^2.8.5",
    "express": "^4.17.2",
    "express-oauth2-jwt-bearer": "^1.1.0",
    "npm-run-all": "^4.1.5"
  }
```

Client packages
```
  "dependencies": {
    "@auth0/auth0-spa-js": "^1.19.4",
    "axios": "^0.25.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuetify": "^2.4.0"
  }
```

**Comment by adamjmcgrath** [comment]
Hi @rashidmya - thanks for raising this

> Failed to fetch authorization server metadata

Your error tells me that the url for your issuer is incorrect or your issuer doesn't provide authorization server metadata

Could you let me know what value you are providing for your [issuerBaseURL](https://auth0.github.io/node-oauth2-jwt-bearer/interfaces/authoptions.html#issuerbaseurl)?

**Comment by rashidmya** [comment]
the value of my **issuerBaseURL** is my client url: http://localhost:8000

**Comment by adamjmcgrath** [comment]
Hi @rashidmya - Your issuer is your identity provider (eg `your-tenant.auth0.com`)

**Comment by meyvan** [comment]
> Hi @rashidmya - Your issuer is your identity provider (eg `your-tenant.auth0.com`)

Mate, Im having the same issue in React

I tried with a combination of : 

    "audience": "https://MYAUDIENCE.au.auth0.com/api/v2/",
    "issuerBaseURL": "https://TENANT.us.auth0.com",

The above did not work, I received:

`{
    "message": "no applicable key found in the JSON Web Key Set"
}`

So I tried the below:

    "audience": "https://MYAUDIENCE.au.auth0.com/api/v2/",
   "issuer": "https://TENANT.us.auth0.com",
    "jwksUri": "https://TENANT.us.auth0.com/.well-known/jwks.json"

But I get:

`{
    "message": "Failed to fetch authorization server metadata"
}`

I'm not new to Auth0, have been successfully running production systems. But I created something from scratch for my personal project and its not working

**Comment by adamjmcgrath** [comment]
@meyvan - if you can share your value for `TENANT` I might be able to investigate.

@rashidmya - let me know if updating `issuerBaseURL` to your issuer worked for you and I'll close this issue

**Comment by meyvan** [comment]
@adamjmcgrath my tenant is `dev-qnsy8uhz` . please let me know if I'm doing something wrong

**Comment by adamjmcgrath** [comment]
> "issuerBaseURL": "https://TENANT.us.auth0.com",

@meyvan I'm able to fetch your authz server metadata using https://dev-qnsy8uhz.us.auth0.com/.well-known/openid-configuration

I noticed that you're mixing `au.auth0.com` and `us.auth0.com` in places, could you perhaps be using the `au` one as your issuer by mistake? If not, then I can only assume your server is not connected to the internet?

**Comment by meyvan** [comment]
@adamjmcgrath I ended up using https://github.com/auth0/node-jwks-rsa , it works for my scenario. Thank you
