### ISSUE TITLE
Export `jwtVerifier` in express-oauth2-jwt-bearer

### ISSUE THREAD

**Issue by andersevenrud** [auth0/node-oauth2-jwt-bearer#59]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm currently securing an API using this library, which has been working great. But now I find myself looking at ways to also add some security to websocket connections.

Currently the only way to access the features of [access-token-jwt](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/access-token-jwt) is to use the middleware provided by [express-oauth2-jwt-bearer](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer).

It would be nice to have a way to access some of these from express-oauth2-jwt-bearer exports.

### Describe the ideal solution

```js
import { jwtVerifier } from 'express-oauth2-jwt-bearer'

// Yay! I can verify tokens without having to use middleware
const verifyJwt = jwtVerifier(opts)
```

## Alternatives and current work-arounds

I'm currently mocking the `(req, res, next)` function arguments for the middleware in order to make this work that goes something like this... which is quite messy, especially with typescript :sweat_smile: 

```js
import { auth } from 'express-oauth2-jwt-bearer'

// ...

const auther = auth({})

const mockAuth = (token) => new Promise((resolve, reject) => {
  const req = {
    /* .. some stuff here */
    headers: {
      authorization: `Bearer ${token}`
    }
  }

  const res = {}

  auther(req, res, (error) => error ? reject(error) : resolve())
})

// ...

router.use(auther)

app.ws('/path', (ws, upgradeReq) => {
  /* Some stuff here that can verify the upgradeReq (cookie value) as well as any ws
     messages (w/embedded token) using mockAuth(token) and then do a ws.close() with
     custom code and reason to make client-side app display correct message */
})
```

The only proper alternative looks to be installing other libraries to handle the same job.

### Additional context

Sorry if there's something obvious I'm missing here both in terms of these packages and/or how to best deal with my websocket situation.

**Comment by adamjmcgrath** [comment]
Hi @andersevenrud - thanks for raising this

Currently this monorepo supports one SDK for express only. We'd like to support different frameworks and platforms in the future and your request for Websocket support is useful. I'll add it to our product list.

**Comment by formula1** [comment]
I'm also interested in websocket support. For my purposes its relatively simple

```javascript
const TOKEN_RE = /^Bearer (.+)$/i;
async function getAuthFromWebsocket(websocket){
  const headersMessage = await Promise.race([
    waitForMessage(websocket),
    delay(2000).then(()=>(throw new Error("timed out")))
  ]);
  const validHeaders = JSON.parse(headersMessage.data);
  if(!TOKEN_RE.test(validHeaders.authorization)){
    throw new Error("need authorization header")
  }
  return verifyJwt(jwt)
}
```
https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer/src/index.ts#L82


Otherwise we have to copy the [access-web-token repo](https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/access-token-jwt) which may miss out on any fixes you end up doing there

**Comment by dounan** [comment]
@adamjmcgrath Any updates on adding support for websocket (or just simply exposing jwtVerifier)? I have the same use case and am currently resorting to forking the code

**Comment by adamjmcgrath** [comment]
Hi @dounan - no updates I'm afraid, I'm not sure when we might be able to prioritise work for either of those 2 at the moment
