### ISSUE TITLE
Fetching subject from JWT?

### ISSUE THREAD

**Issue by another-dave** [auth0/node-oauth2-jwt-bearer#60]
### Description

I'm trying to get the `sub` after JWT validation, following the sample code [in the introductory blogpost](https://auth0.com/blog/introducing-oauth2-express-sdk-protecting-api-with-jwt/), but I'm hitting an error:

```plain
TypeError: Cannot read properties of undefined (reading 'payload')
    at $PROJECT_ROOT/index.js:9:41
    at Layer.handle [as handle_request] ($PROJECT_ROOT/node_modules/express/lib/router/layer.js:95:5)
    at next ($PROJECT_ROOT/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch ($PROJECT_ROOT/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] ($PROJECT_ROOT/node_modules/express/lib/router/layer.js:95:5)
    at $PROJECT_ROOT/node_modules/express/lib/router/index.js:284:15
    at Function.process_params ($PROJECT_ROOT/node_modules/express/lib/router/index.js:346:12)
    at next ($PROJECT_ROOT/node_modules/express/lib/router/index.js:280:10)
    at $PROJECT_ROOT/node_modules/express-oauth2-jwt-bearer/dist/index.js:355:13
 ```   

#### Sample package.json

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "express-oauth2-jwt-bearer": "^1.1.0"
  }
}
```

#### Set-up
* Save sample code as `index.js`
* Create `.env` file as per blogpost with `ISSUER_BASE_URL` and `AUDIENCE` defined.

#### Running

```
nvm use 16
npm install
node index.js
```

* If I remove the reference to `res.auth` (e.g. making the response message just `Hello!`), I don't hit an error.
* I'm testing with a Bearer token that I received from an SPA hitting Auth0 directly. I can see a valid exchange in the Logs on the dashboard.
* If I manually put the token through `echo ... | base64 --decode` the signature and body look fine & I can see the subject/aud/scopes etc.

### Environment

> Please provide the following:

- **Version of this library used:** `1.1.0`
- **Version of the platform or framework used, if applicable:** Node 16.15.0
- **Other relevant versions (language, server software, OS, browser):** macOS 12 (monterey)
- **Other modules/plugins/libraries that might be involved:** dotenv (`16.0.1`), express (`4.18.1`)

Please let me know if I can give any other details.

**Comment by adamjmcgrath** [comment]
Hi @another-dave - thanks for raising this

You've spotted a typo in the blog post, the code sample should read `req.auth.payload.sub` not `res.auth.payload.sub`

I'll get that fixed
