### ISSUE TITLE
Support checking permissions instead of scope

### ISSUE THREAD

**Issue by jarlbrak** [auth0/node-oauth2-jwt-bearer#67]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> Like you folks did in the express-jwt-authz library, I need the ability to check the permissions of a jwt instead of the scopes.

### Describe the ideal solution

> 'requiredScopes' should work similar to express-jwt-authz where I can simply switch to check against the jwt permissions.

## Alternatives and current work-arounds

> Only workaround (that I can't get to work lately) is https://github.com/auth0/express-jwt-authz

### Additional context

> None

**Comment by adamjmcgrath** [comment]
Hi @jarlbrak - thanks for raising this

This question has already been answered here https://github.com/auth0/node-oauth2-jwt-bearer/issues/58

**Comment by jarlbrak** [comment]
Ah, interesting. Thanks for the pointer, surprised I didn't see that before. It might be helpful to put some of this guidance in the Auth0 docs since now that authz is deprecated, there is no guidance on how to do this in this new package.
