### ISSUE TITLE
InvalidTokenError: Invalid Compact JWS

### ISSUE THREAD

**Issue by patzj** [auth0/node-oauth2-jwt-bearer#69]
### Description

> I'm using the `auth` middleware to protect a certain endpoint. The issue is when I use the access token _(as bearer token)_ coming from `getAccessTokenSilently` of [@auth0/auth0-react](https://github.com/auth0/auth0-react). I'm getting `InvalidTokenError: Invalid Compact JWS` in the logs. But when I use the `__raw` claim from `getIdTokenClaims`, it works. I'm confused whether this lib is suppose to verify access token or ID token.

### Reproduction

1. Set up node-express app (server)
```ts
const jwtCheck = auth({
  issuerBaseURL: "<DOMAIN>",
  audience: "<CLIENT_ID>",
});

app.get("/signIn", jwtCheck, async (req, res) => {
  if (req.auth) {
    return res.send("OK");
  }

  return res.status(401).send("Unauthorized");
});
```

2. Set up react app (client)
```tsx
export default function Home() {
  const auth0 = useAuth0();

  function signIn() {
    auth0.loginWithRedirect();
  }

  function signOut() {
    auth0.logout({
      returnTo: window.location.origin,
    });
  }

  useEffect(() => {
    if (auth0.isAuthenticated) {
      auth0.getAccessTokenSilently().then((token) => {
        fetch("/signIn", {
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        })
          .then((res) => res.text())
          .then((text) => console.log(text))
          .catch((error) => console.error(error));
      });
    }
  }, [auth0]);

  if (!auth0.user) {
    return <button onClick={signIn}>Sign In</button>;
  }

  return (
    <div>
      <span>{auth0.user.name}</span>&nbsp;
      <button onClick={signOut}>Sign Out</button>
    </div>
  );
}
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.1.0
- **Version of the platform or framework used, if applicable:** express@4.18.1
- **Other relevant versions (language, server software, OS, browser):** typescript, firebase cloud function, firebase hosting
- **Other modules/plugins/libraries that might be involved:** @auth0/auth0-react@1.10.2

**Comment by adamjmcgrath** [comment]
Hi @patzj - thanks for raising this

> I'm confused whether this lib is suppose to verify access token or ID token.

This lib is designed to verify access token JWTs

When you login to Auth0 and don't specify an Audience, you will get an [opaque access token](https://auth0.com/docs/secure/tokens/access-tokens#opaque-access-tokens). It looks like a regular JWT, but actually it's a self contained encrypted JWT. The only way to validate an opaque token is to call the server that issued the token, in this case the `/userinfo` endpoint.

In order to get an [access token JWT](https://auth0.com/docs/secure/tokens/access-tokens#jwt-access-tokens). You need to [create a custom api](https://auth0.com/docs/get-started/auth0-overview/set-up-apis). Then use this as the `audience` in your react app to login:

```js
<Auth0Provider
      domain="YOUR_AUTH0_DOMAIN"
      clientId="YOUR_AUTH0_CLIENT_ID"
      redirectUri={window.location.origin}
      audience="YOUR_API_IDENTIFIER"
```

This will give you an access token JWT when you call `getAccessTokenSilently`.

Then you can specify the same API Identifier as the audience in your api

```js
const jwtCheck = auth({
  issuerBaseURL: "https://<DOMAIN>", 
  audience: "YOUR_API_IDENTIFIER",
});
```

**Comment by patzj** [comment]
Thank you @adamjmcgrath. It worked.

**Comment by formula1** [comment]
This solution isn't working well with typescript as audience is defined in the properties

https://auth0.github.io/auth0-react/functions/Auth0Provider.html

**Comment by formula1** [comment]
```typescript
<Auth0Provider
        domain={AUTH0_CLIENT_DOMAIN}
        clientId={AUTH0_CLIENT_ID}
        authorizationParams={{
          redirect_uri: window.location.origin,
          audience: AUTH0_AUDIENCE,
        }}
>
  <YourApp />
</Auth0Provider>
```

**Comment by adamjmcgrath** [comment]
> This solution isn't working well with typescript as audience is defined in the properties

@formula1 - that example was for auth0-react v1, thank you for providing an example for react v2

**Comment by matgott** [comment]
With opaque tokens are we only able to retrieve the user profile? How do we check that the token is not expired?

I have a react native app that uses Auth0 to authenticate users and I'm not using an Auth0 API to get JWT tokens. If the token's expired the /userinfo endpoint won't retuns anything?

**Comment by RamanSB** [comment]
Why does the `Auth0Provider` component from `import { useAuth0, Auth0Provider } from "react-native-auth0";` not include authorizationParameters as a prop?
![image](https://github.com/auth0/node-oauth2-jwt-bearer/assets/13969478/e46a7edc-f459-432a-9d13-90459ce6536d)

**Comment by moabz49** [comment]
> ```js
> <Auth0Provider
>         domain={AUTH0_CLIENT_DOMAIN}
>         clientId={AUTH0_CLIENT_ID}
>         authorizationParams={{
>           redirect_uri: window.location.origin,
>           audience: AUTH0_AUDIENCE,
>         }}
> >
>   <YourApp />
> </Auth0Provider>
> ```

THANKS @formula1 this solved my problem

**Comment by ThomasSpare** [comment]
import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter as Router } from "react-router-dom";
import { Auth0Provider } from "@auth0/auth0-react";
import App from "./App";
import authConfig from "./auth_config.json";

const container = document.getElementById("root");
const root = createRoot(container);

root.render(
  <Auth0Provider
    domain={authConfig.domain}
    clientId={authConfig.clientId}
    redirectUri={window.location.origin}
    authorizationParams={{
      redirect_uri: window.location.origin,
      audience: authConfig.audience,
    }}
  >
    <Router>
      <App />
    </Router>
  </Auth0Provider>
);


In my index.js file:
This solved it for me. I've spent days trying to figure this out.
