### ISSUE TITLE
How to stop node-oauth2-jwt-bearer from polluting my output

### ISSUE THREAD

**Issue by rococtz** [auth0/node-oauth2-jwt-bearer#70]
I am using this package for an express app running on AWS Lambda which prints all output to CloudWatch:
```javascript
import { auth } from 'express-oauth2-jwt-bearer';

export default auth({
  jwksUri: ...,
  issuer: ...,
  audience: ...,
});
```
The issue is that every time someone tries to access my endpoints with an expired token (or invalid, or without token), the package throws some errors such as this one:
`InvalidTokenError: "exp" claim timestamp check failed`

**Question:**
How do I catch those before they hit the console? I don't want them to reach CloudWatch at all.

I tried wrapping the code with `try/catch` but it doesn't stop the error from going to console:
```javascript
const authFn = auth({...});

export default async (req, res, next) => {
  try {
    const result = await authFn(req, res, next);
  } catch(e) {
    // handle error
  }
};
```

**Comment by adamjmcgrath** [comment]
Hi @rococtz - thanks for raising this

All this package's errors are caught and handled by Express (see https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer/src/index.ts#L76)

This is how errors should be handled in Express, see https://expressjs.com/en/guide/error-handling.html#catching-errors

I'm not sure what mechanism is causing those entries to show in your Cloudwatch logs, perhaps it's the [default Express error handler](https://expressjs.com/en/guide/error-handling.html#the-default-error-handler) - is your `NODE_ENV` set correctly? Also, you could have a look at [writing your own error handler](https://expressjs.com/en/guide/error-handling.html#writing-error-handlers)

**Comment by rococtz** [comment]
@adamjmcgrath This is very helpful, thank you very much.

**Comment by isaachinman** [comment]
@rococtz @adamjmcgrath I've seen identical `InvalidTokenError: "exp" claim timestamp check failed` errors, despite my JWTs being set to a 30 day expiry (in the Auth0 dashboard).

For my user base, this means that expired tokens should almost never happen, yet I see these errors many times per day.

Any hints as to how these errors can be debugged? As @rococtz hints at, even reqs without a token end up spitting out `"exp" claim timestamp check failed`, so I have a feeling this error block is unintentionally catching many other errors.

**Comment by adamjmcgrath** [comment]
Hi @isaachinman 

> As @rococtz hints at, even reqs without a token end up spitting out "exp" claim timestamp check failed, so I have a feeling this error block is unintentionally catching many other errors.

I don't think that's what they're saying. And I don't see how this would be possible since [`UnauthorizedError` will be thrown if there is no token on the request](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/oauth2-bearer/src/get-token.ts#L59), and the part of code that validates the claims will not be reachable.

If you think there is a bug with this SDK, could you raise a new issue and share an example repo that demonstrates the bug and I'd be happy to debug it.

**Comment by rococtz** [comment]
@isaachinman I was getting the expired token error because it was truly expired :) The error was relevant so my only issue was that I was not catching the right way which is by using `next()`.
