### ISSUE TITLE
Add an additional agnostic and lightweight solution to build on top

### ISSUE THREAD

**Issue by jferrettiboke** [auth0/node-oauth2-jwt-bearer#71]
### Describe the problem you'd like to have solved

I have successfully implemented `express-oauth2-jwt-bearer` in a Next.js app using [API Routes](https://nextjs.org/docs/api-routes/introduction).

I run into some incompatibility issues but I managed to solve them. For instance, `express-oauth2-jwt-bearer` uses `req.is()` [here](https://github.com/auth0/node-oauth2-jwt-bearer/blob/1b106295187199380a364788d3b6edd32b49457c/packages/express-oauth2-jwt-bearer/src/index.ts#L71), but it is not available in Next.js API Routes. This made me implement workarounds.

Another thing that I have noticed is the size of the package. Why is this package bloated? [Here](https://bundlephobia.com/package/express-oauth2-jwt-bearer) is what bundlephobia.com reports. And this (see screenshot below) is what the [Import Cost VSCode Extension](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost) reports when importing `auth`.

![Screenshot 2022-09-01 at 12 02 21](https://user-images.githubusercontent.com/11066224/187888240-115e24c3-25d2-4313-8ce4-cdaabb487d54.png)

I guess most of the code comes from `jose`. But, can we reduce it even more? I'm thinking on tree shaking. This could have a huge impact on serverless environments. ⚡️

### Describe the ideal solution

It would be awesome if you guys could ship an agnostic and lightweight solution. I'm thinking of a low-level solution, so other developers can build on top of it to satisfy their needs or create more integrations with their preferred Node.js frameworks (while the official is not ready yet).

## Alternatives and current work-arounds

Publishing [access-token-jwt](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/access-token-jwt) and [oauth2-bearer](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/oauth2-bearer) could help.

**Comment by adamjmcgrath** [comment]
Hi @jferrettiboke - thanks for raising this

> Publishing [access-token-jwt](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/access-token-jwt) and [oauth2-bearer](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/oauth2-bearer) could help.

Yep 👍 we'd like to do this at some point, no timeline yet though I'm afraid

Closing in favour of #63
