### ISSUE TITLE
Add support for node 18

### ISSUE THREAD

**Issue by ricardasnav** [auth0/node-oauth2-jwt-bearer#76]
### Describe the problem you'd like to have solved

In my project I use node v18.8.0, however I get the following error: 
error express-oauth2-jwt-bearer@1.1.0: The engine "node" is incompatible with this module. Expected version "12.19.0 || ^14.15.0 || ^16.13.0". Got "18.8.0"

Any chance you would add support for the node 18 any time soon?
Thank you

**Comment by adamjmcgrath** [comment]
Hi @ricardasnav - thanks for raising this

We rely on our cryptography library's support for Node, which only supports LTS versions (see https://github.com/panva/jose/issues/262)

As soon as Node 18 is in LTS ([2022-10-25](https://github.com/nodejs/release#release-schedule)) We'll add it to the engines

Going to close this, but feel free to ping me if it gets to 2022-10-25 and I forget to update

**Comment by manvydasu** [comment]
@adamjmcgrath 
Can you add Node 18, please? It's LTS already.

**Comment by adamjmcgrath** [comment]
@manvydasu - added this to https://github.com/auth0/node-oauth2-jwt-bearer/releases/tag/v1.2.0
