### ISSUE TITLE
Supported engines does not include the latest node LTS, 18.12.0

### ISSUE THREAD

**Issue by aejay-rs** [auth0/node-oauth2-jwt-bearer#78]
### Description

The new node LTS has now entered support, 18.12.0, and consuming application CI steps that target the latest LTS are now broken, as this version is not included in the supported engines.  

### Reproduction

1. Install node 18.12.0 (or use a hosted CI agent that targets it as the latest LTS)
2. Reference the library from a project
3. Run either `npm install` or `npm ci`

Step 3 results in a `code EBADENGINE` error due to 18.12.0 not falling within the allowed engines spec: `{"node":"12.19.0 || ^14.15.0 || ^16.13.0"}`

### Environment

- Library version for our incident:  express-oauth2-jwt-bearer@1.1.0
- node version: 18.12.0
- System: Github-hosted Actions agent, Ubuntu LTS 20.04.5

**Comment by aejay-rs** [comment]
It should be noted that in our case, the temporary workaround is straightforward: instruct the github action to target the `16.x` version of node specifically, rather than the latest LTS, and avoid using the `18.x` version on our local machines until a version of this package is available that supports it.

So there is nothing here that stops our momentum, but I assume you're going to see more folks run into this as people upgrade to the latest LTS.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @aejay-rs 

Have added this to https://github.com/auth0/node-oauth2-jwt-bearer/releases/tag/v1.2.0
