### ISSUE TITLE
Proposal: add support for `scopesIncludesAny` 

### ISSUE THREAD

**Issue by manvydasu** [auth0/node-oauth2-jwt-bearer#83]
### Describe the problem you'd like to have solved

`express-oauth2-jwt-bearer`

Currently for checking scopes there is only one function exposed by the library `requiredScopes`. It coves the cases, when **all provided scopes must be included in the token**. However, if there is a need to allow access based on OR condition (i.e. require either scope A or scope B), that can not be implemented without writing custom logic for checking scopes.

### Describe the ideal solution

A new utility function called `scopesIncludesAny` (or something similar) is exposed by the library.
It would work by checking if at least one of the provided scopes exist in the `payload.scope` property. 
I.e. `scopesIncludesAny(['A', 'B'])` - would return true if:

-  payload contains scope A, 
-  payload contains scope B,
-  or payload contains scope A and B. 

  
 If there isn't scope A or scope B in the payload, error will be thrown.

## Alternatives and current work-arounds

Custom utility function can be written by the library user, which adds missing behaviour.

**Comment by adamjmcgrath** [comment]
Hey @manvydasu - thanks for the suggestion

Sounds reasonable, I don't know when we might get a chance to look at this, but always happy to consider a PR

**Comment by ewanharris** [comment]
Hey @manvydasu 👋🏻  We just shipped the new `scopeIncludesAny` middleware in version 1.3.0 of this package, you can [check the docs](https://auth0.github.io/node-oauth2-jwt-bearer/index.html#scopeincludesany) for more info.

Thanks for the suggestion!

**Comment by manvydasu** [comment]
@ewanharris 
Will check it out, thank you!
