### ISSUE TITLE
Document upgrade path from "express-jwt" + "jwks-rsa"

### ISSUE THREAD

**Issue by heidemn-faro** [auth0/node-oauth2-jwt-bearer#87]
### Describe the problem you'd like to have solved

Previously, the official Auth0 docs recommended the use of `express-jwt` + `jwks-rsa` for Express APIs.
Therefore, many people might want to crossgrade from these libs to `express-oauth2-jwt-bearer`,
especially since the sub-dependency footprint was reduced a lot - 35 vs. 2 packages 🎉 

### Describe the ideal solution

The documentation should describe things to consider when crossgrading from `express-jwt` + `jwks-rsa` to `express-oauth2-jwt-bearer`.
* how to adapt the code (okay this one is more or less clear):
  Mostly change from `req.user` or `req.auth` to `req.auth?.payload`
* are error handling, retries, timeouts different (e.g. when fetching the public key)?
* is anything no longer supported, compared to the previous libs?
* any other changes in behavior that might not be obvious

## Alternatives and current work-arounds

Developers can try to figure out themselves, and discover unexpected changes in production.

### Additional context

n/a

**Comment by adamjmcgrath** [comment]
Hi @heidemn-faro - thanks for the suggestion

Documentation about migrating from other libraries is out of scope for this repository, but your suggestion would make a great blog post. I'll recommend it to the developer marketing team, thanks
