### ISSUE TITLE
[example] How to write unit tests for our Express APIs with canned JWTs?

### ISSUE THREAD

**Issue by heidemn-faro** [auth0/node-oauth2-jwt-bearer#90]
### Describe the problem you'd like to have solved

The basic usage of this library is well documented.

In the real world though, developers also have to write tests.
One kind of test that we would like to have is the following:

* Testing API requests against our Express API on localhost (e.g. using mocha + supertest).
* Using canned JWTs (e.g. a malformed one, or one including a particular subject and scopes).
* The library should ignore both the signature and any timestamps in the JWT, so the test can be run any time later.
* Since the signature should be ignored, there's also no point in fetching the JWKS in this case.
  E.g. if we rotate our Auth0 signing key, this kind of test should not be affected.

The goal is to use most of the code in `node-oauth2-jwt-bearer` in these tests, so e.g. the error handling is 99% equal to production.
I'm aware that we can mock away the library entirely, but then we can no longer be sure that our tests match what is happening in production.

### Describe the ideal solution

A short guide or example is provided.

## Alternatives and current work-arounds

Developers can try to figure out themselves, wasting time.

### Additional context

Didn't find what I was looking for here:
* https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/examples
* https://auth0.com/docs/quickstart/backend/nodejs/01-authorization

Example how I imagine it could work:

```js
const { auth } = require('express-oauth2-jwt-bearer');
const isTest = process.env.NODE_ENV === 'test';

app.use(
    auth({
      issuerBaseURL: 'https://YOUR_ISSUER_DOMAIN',
      audience: 'https://my-api.com',
      unsafeIgnoreSignature: isTest,
      unsafeIgnoreTimestamps: isTest,
    })
);
```

Alternative example:

```js
const { auth, authMockForTests } = require('express-oauth2-jwt-bearer');
const isTest = process.env.NODE_ENV === 'test';

app.use(
    isTest ?
    // authMockForTests doesn't validate signatures or timestamps, and doesn't load JWKS.
    authMockForTests({
      issuerBaseURL: 'https://YOUR_ISSUER_DOMAIN',
      audience: 'https://my-api.com',
    })
    :
    auth({
      issuerBaseURL: 'https://YOUR_ISSUER_DOMAIN',
      audience: 'https://my-api.com',
    })
);
```

**Comment by adamjmcgrath** [comment]
Hi @heidemn-faro - thanks for raising this

There are lots of ways you can test JWTs and it would be out of scope of this SDK to teach you - so I'm going to close this.

I tend to avoid adding test code to the actual deployable code - so I wouldn't recommend checking the `NODE_ENV` at runtime personally, but if you want to - you can use the [validators](https://auth0.github.io/node-oauth2-jwt-bearer/interfaces/authoptions.html#validators) config to disable specific claim checks and use things like expired JWTs to test.

There's some good examples of testing JWTs in this repo if you take a look at the code. Namely https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/access-token-jwt/test/helpers.ts#L25 - in this example we generate an asymmetric key pair for each test and make the public key available using `nock` and sign the test JWT with the private key - so this is a good option if you want to do integration style tests with the library.

For unit tests, you can of course stub the auth middleware all together.
